version: 2
orbs:
  go: circleci/go@1.7.3
jobs:
  build:
    environment:
      # Configure the JVM and Gradle to avoid OOM errors
    docker:
      - image: anggit86/android-sdk:latest
    steps:
      - checkout
      - run:
          name: Clone
          command: git clone https://Blawuken:$GH_TOKEN@github.com/Blawuken/v2rayNG
      - run:
          name: Procces
          command: |
              cd v2rayNG
              dos2unix ./gradlew
              ./gradlew --no-daemon assemble
      - run:
          name: Sign
          command: |
              cd v2rayNG
              apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*arm64-v8a.apk
              apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*armeabi-v7a.apk
              apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*x86.apk
              apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*x86_64.apk
              apksigner sign --key platform.pk8 --cert platform.x509.pem app/build/outputs/apk/release/*universal.apk
      - store_artifacts:
          path: v2rayNG/app/build/outputs/apk/release
          destination: Neko-ray

#      - run:
#          name: "Publish Release on GitHub"
#          command: |
#            VERSION=v1.1.7
#            ghr -t ${GH_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} v2rayNG/app/build/outputs/apk/release

workflows:
  version: 2
  workflow:
    jobs:
    - build
