name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Prepare
        run: |
          sudo apt-get -y install dos2unix

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.2'
          cache: false

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          dos2unix ./gradlew
          ./gradlew assemble

      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: UWU-TEAM/Neko-ray
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.MY_TOKEN }}
          files: |
            ${{ github.workspace }}/app/build/outputs/apk/release/*arm64-v8a.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*armeabi-v7a.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*x86.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*x86_64.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*universal.apk

      - name: Generate Changelog
        uses: smichard/conventional_changelog@2.0.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git User Info
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'

      - name: Commit Changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs: :robot: changelog file generated" || echo "No changes to commit"
          git push
