name: Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          sudo apt-get -y install dos2unix
          wget -qO - https://api.github.com/repos/UWU-TEAM/AndroidLibXrayLite/releases/latest \
          | grep browser_download_url | cut -d '"' -f 4 \
          | wget -i - -O app/libs/libv2ray.aar

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Build
        run: |
          dos2unix ./gradlew
          ./gradlew assembleRelease

      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repository: UWU-TEAM/Neko-ray
          body_path: ${{ github.workspace }}/CHANGELOG.md
          token: ${{ secrets.MY_TOKEN }}
          files: |
            ${{ github.workspace }}/app/build/outputs/apk/release/*arm64-v8a.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*armeabi-v7a.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*x86.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*x86_64.apk
            ${{ github.workspace }}/app/build/outputs/apk/release/*universal.apk
