name: Update Gradle wrapper

on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
    branches:
      - dev

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: JDK Setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@main
        with:
          target-branch: main
          repo-token: ${{ secrets.MY_TOKEN }}
          set-distribution-checksum: true
          paths: gradle/wrapper/*
